name: CI Pipeline
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Set up Python3
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install Dependencies
        run: pip install pytest

      - name: Run tests
        run: pytest

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Set up Python3
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install flake8
        run: pip install flake8

      - name: Run flake8
        run: flake8 Programowanie/Tests/cezar.py Programowanie/Tests/test_Cezar.py
